export const movies = [
  {
    id: 1,
    imageUrl: "https://www.imdb.com/title/tt0056761/mediaviewer/rm846926080/",
    movieTitle: "The Great Adventure",
    rating: 8.5,
    duration: "2h 30m",
    language: "English",
    seatsAvailable: 50,
    pricePerSeat: 150,
    location: "Mumbai",
  },
  {
    id: 2,
    imageUrl: "https://via.placeholder.com/200x300.png?text=Movie+2",
    movieTitle: "Love in Paris",
    rating: 7.2,
    duration: "1h 45m",
    language: "French",
    seatsAvailable: 30,
    pricePerSeat: 200,
    location: "Delhi",
  },
  {
    id: 3,
    imageUrl: "https://via.placeholder.com/200x300.png?text=Movie+3",
    movieTitle: "Warrior's Creed",
    rating: 9.0,
    duration: "3h 10m",
    language: "Hindi",
    seatsAvailable: 100,
    pricePerSeat: 100,
    location: "Bangalore",
  },
  {
    id: 4,
    imageUrl: "https://via.placeholder.com/200x300.png?text=Movie+4",
    movieTitle: "Mystery in the Woods",
    rating: 6.8,
    duration: "2h",
    language: "English",
    seatsAvailable: 20,
    pricePerSeat: 250,
    location: "Chennai",
  },
  {
    id: 5,
    imageUrl: "https://via.placeholder.com/200x300.png?text=Movie+5",
    movieTitle: "Galactic Odyssey",
    rating: 8.9,
    duration: "2h 45m",
    language: "Japanese",
    seatsAvailable: 75,
    pricePerSeat: 180,
    location: "Hyderabad",
  },
];
