package com.thewa.fastpost.constant;
public enum DeliveryStatus {
	BOOKED,
	COLLECTED_AT_SOURCE,
	ON_ITS_WAY,
	OUT_FOR_DELIVERY,
	DELIVERED,
	FAILED_ATTEMPT,
	RETURNED_TO_SENDER,
	CANCELLED,
	NOT_DELIVERED,
	PENDING,
	LOST_IN_TRANSIT,
	DAMAGED_IN_TRANSIT
}